name: Cypress tests
on: [push, pull_request]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # the actual items in the array do not matter,
        # just the number - to force CI to sping 3 copies
        # of the current job in parallel
        machines: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: oven-sh/setup-bun@v1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - name: Install dependencies
        run: bun install
      - name: Run e2e
        run: bun run e2e
